version: "3"

services:
  erlang_influxdb:
    image: influxdb:1.8.10-alpine
    platform: linux/x86_64
    container_name: erlang_influxdb
    ports:
      - 18086:8086
      - 18088:18088
    environment:
      - "INFLUXDB_ADMIN_ENABLED=true"
      - "INFLUXDB_DB=GreyOrange; CREATE DATABASE collectd; CREATE DATABASE logstash"
      - "INFLUXDB_REPORTING_DISABLED=true"
      - "INFLUXDB_HTTP_LOG_ENABLED=true"
      - "INFLUXDB_HTTP_ACCESS_LOG_PATH=/var/log/influxdb/access.log"
      - "INFLUXDB_DATA_QUERY_LOG_ENABLED=false"
      - "INFLUXDB_COORDINATOR_LOG_QUERIES_AFTER=1s"
      - "INFLUXDB_DATA_MAX_CONCURRENT_COMPACTIONS=2"
      -  "HEALTH_CHECK_PORT=18086"
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - influxdb:/var/lib/influxdb
      - influxdb_logs:/var/log/influxdb


volumes:
  influxdb:
      driver: local
  influxdb_logs:
      driver: local
